BuilderFormByDynamicAttrs/SystemEvent/controllers/DefaultController.php
<?php

namespace app\modules\SystemEvent\controllers;

use app\actions\TogglePropertyAction;
use app\modules\SystemEvent\helpers\SystemEventHelper;
use Yii;
use app\actions\IndexAction;
use app\models\User;
use app\modules\SystemEvent\components\interfaces\BuildByTypeInterface;
use app\modules\SystemEvent\models\form\SystemEventForm;
use app\modules\SystemEvent\models\form\ToggleActiveForm;
use app\modules\SystemEvent\models\SystemEventMailSetting;
use app\modules\SystemEvent\models\SystemEventType;
use app\modules\SystemEvent\models\SystemEvent;
use app\modules\SystemEvent\models\search\SystemEventSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use yii\widgets\ActiveForm;

/**
 * DefaultController implements the CRUD actions for SystemEvent model.
 */
class DefaultController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => [
                            'index',
                            'create',
                            'update',
                            'delete',
                            'build-form',
                            'toggle-active',
                            'batch-operation',
                        ],
                        'allow' => true,
                        'roles' => [
                            User::SYSTEM_EVENT_DISPATCHER_EDIT,
                        ],
                    ],
                    [
                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => [
                            User::SYSTEM_EVENT_LIST,
                        ],
                    ],
                    [
                        'actions' => ['create'],
                        'allow' => true,
                        'roles' => [
                            User::SYSTEM_EVENT_CREATE,
                        ],
                    ],
                    [
                        'actions' => ['update', 'toggle-active', 'batch-operation'],
                        'allow' => true,
                        'roles' => [
                            User::SYSTEM_EVENT_UPDATE,
                        ],
                    ],
                    [
                        'actions' => ['delete'],
                        'allow' => true,
                        'roles' => [
                            User::SYSTEM_EVENT_DELETE,
                        ],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'index' => [
                'class' => IndexAction::class,
                'modelClass' => SystemEventSearch::class,
                'paramsView' => [
                    'actions' => SystemEventHelper::getAllowBatchAction(),
                ],
            ],
        ];
    }

    public function actionCreate()
    {
        $form = new SystemEventForm();
        $model = new SystemEvent();
        if (Yii::$app->request->isPost && $form->load(\Yii::$app->request->post()) && $form->validate()) {
            if ($model = Yii::$app->systemEventManager->create($form)) {
                return $this->redirect(['index']);
            }
        }
        if (Yii::$app->request->isAjax) {
            return $this->asJson(
                [
                    'form' => $this->renderPartial(
                        '_form',
                        [
                            'formBuilder' => Yii::$container->get(BuildByTypeInterface::class),
                            'type' => new SystemEventType(),
                            'model' => $model,
                            'modelForm' => $form,
                        ]
                    ),
                ]
            );
        }

        return $this->render(
            'create',
            [
                'model' => $model,
            ]
        );
    }


    /**
     * @param int $id
     *
     * @return Response
     * @throws NotFoundHttpException
     * @throws \yii\base\InvalidConfigException
     * @throws \yii\di\NotInstantiableException
     * @todo: Сейчас форма инитится из настроек для email уведомлений (событий), далее могут быть другие события
     */
    public function actionUpdate($id)
    {
        /** @var SystemEvent $model */
        $model = $this->findModel($id);
        $form = new SystemEventForm($model->systemEventMailSettings->attributes);
        if (Yii::$app->request->isPost && $form->load(\Yii::$app->request->post()) && $form->validate()) {
            if ($model = Yii::$app->systemEventManager->update($form)) {
                return $this->redirect(['index']);
            }
        }
        $form->event_name = $model->event_name;
        $form->handler = $model->handler;
        if (Yii::$app->request->isAjax) {
            return $this->asJson(
                [
                    'form' => $this->renderPartial(
                        '_form',
                        [
                            'formBuilder' => Yii::$container->get(BuildByTypeInterface::class),
                            'type' => $model->type,
                            'model' => $model,
                            'modelForm' => $form,
                        ]
                    ),
                ]
            );
        }
    }

    /**
     * @param int $id
     *
     * @return Response
     * @throws NotFoundHttpException
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionToggleActive($id)
    {
        /** @var SystemEvent $model */
        $model = $this->findModel($id);
        $form = new ToggleActiveForm(['id' => $id]);
        if ($form->load(Yii::$app->request->post(), '') && $form->validate()) {
            if (Yii::$app->systemEventManager->toggleActiveItem($form)) {
                return $this->asJson(['status' => 200]);
            }
        }

        return $this->asJson(['status' => 500, 'errors' => array_merge($form->errors, $model->errors)]);
    }

    /**
     * @param string $action
     * @param array  $ids
     *
     * @throws NotFoundHttpException
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionBatchOperation(string $action)
    {
        $ids = Yii::$app->request->post('ids');
        switch ($action) {
            case 'enabled':
            case 'disabled':
                foreach ($ids as $id) {
                    $form = new ToggleActiveForm(['id' => $id, 'active' => $action === 'enabled']);
                    if ($form->load(Yii::$app->request->post(), '') && $form->validate()) {
                        $model = Yii::$app->systemEventManager->toggleActiveItem($form);
                        if ($model->errors) {
                            var_dump($model->errors);
                            die;
                        }
                    }
                }
                break;
        }
    }

    /**
     * @param int $id
     *
     * @return \yii\web\Response
     * @throws NotFoundHttpException
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete($id)
    {
        Yii::$app->systemEventManager->delete($id);

        return $this->redirect(['index']);
    }

    /**
     * @param int $id
     *
     * @return string
     * @throws \Exception
     */
    public function actionBuildForm($id)
    {
        $type = SystemEventType::findOne($id);

        return $this->asJson(
            [
                'form' => $this->renderPartial(
                    '_form_builded_by_type',
                    [
                        'formBuilder' => Yii::$container->get(BuildByTypeInterface::class),
                        'type' => $type,
                        'model' => new SystemEventForm(
                            [
                                'type_handle' => $id,
                            ]
                        ),
                        'systemEvent' => new SystemEvent(),
                    ]
                ),
            ]
        );
    }

    /**
     * @return array
     */
    public function actionValidationFormBuild()
    {
        $model = new SystemEventForm();
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;

            return ActiveForm::validate($model);
        }
    }

    /**
     * @param integer $id
     *
     * @return SystemEvent the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    private function findModel($id)
    {
        if (($model = SystemEvent::findOne($id)) !== null) {
            return $model;
        }
        throw new NotFoundHttpException(Yii::t('app', 'The requested model #{id} does not exist.', ['{id}' => $id]));
    }
}

BuilderFormByDynamicAttrs/SystemEvent/views/default/_form.php
<?php

use yii\web\View;
use yii\helpers\Html;
use app\widgets\Select;
use yii\bootstrap\Modal;
use yii\bootstrap\Alert;
use yii\widgets\ActiveForm;
use app\modules\SystemEvent\models\SystemEvent;
use app\modules\SystemEvent\components\FormBuilder;
use app\modules\SystemEvent\models\SystemEventType;
use app\modules\SystemEvent\helpers\SystemEventHelper;
use app\modules\SystemEvent\models\form\SystemEventForm;

/**
 * @var View            $this
 * @var SystemEvent     $model
 * @var ActiveForm      $form
 * @var FormBuilder     $formBuilder
 * @var SystemEventType $type
 * @var SystemEventForm $modelForm
 */
?>
<?php Modal::begin(
    [
        'closeButton' => false,
        'options' => [
            'class' => 'fade modal',
        ],
        'header' => '<div style="float:left;margin-right: 15px;">' . Yii::t(
            'app',
            $model->isNewRecord ? 'Добавление события\обработчика' : 'Обновление события\обработчика'
        ) . '</div>' . (!$model->isNewRecord ? '<div id="js-checkbox-toggle"></div>' : ''),
        'footer' => '<div class="row">
                        <div class="col-lg-12"></div>
                        <div class="col-lg-12">' .
            Html::button(
                Yii::t('app', 'Закрыть'),
                [
                    'style' => 'margin-right:15px',
                    'class' => 'btn btn-outline btn-outline--green',
                    'data-dismiss' => 'modal',
                ]
            ) .
            Html::button(
                $model->isNewRecord ? Yii::t('app', 'Добавить') : Yii::t('app', 'Сохранить'),
                ['class' => 'btn btn-green js-submit', 'disabled' => $model->isNewRecord]
            )
            . '</div></div>',
    ]
); ?>

<?= Html::errorSummary($type, ['class' => 'alert alert-danger']) ?>
<?php $form = ActiveForm::begin(['options' => ['autocomplete' => 'off']]); ?>
<div class="row">
    <div class="col-md-24">
        <?php if ($model->isNewRecord): ?>
            <?= $form->field($type, 'id')->widget(
                Select::class,
                [
                    'options' => [
                        'class' => 'form-control js-handler',
                        'data-style' => 'btn-sm btn-default',
                        'prompt' => '—',
                    ],
                    'items' => SystemEventHelper::getListSystemEventType(),
                ]
            )->label('Выберите тип обработчика события') ?>
        <?php endif; ?>
        <div class="flash-alerts" style="display:none;background:#fff;width:100%;position:absolute;top:0;left:0;z-index:9999;padding-top: 10px;">
            <div style="width: 100%;" class="alert alert-dismissible attention">
                <div id="message"></div>
            </div>
        </div>
        <input type="hidden" name="SystemEventForm[type_handle]" id="js-type-event" value="<?= $type->id ?>">
        <div class="js-handler-params">
            <?php if (!$model->isNewRecord): ?>
                <input type="hidden" name="SystemEventForm[system_event_id]" id="systemEventId" value="<?= $model->id ?>">
                <input type="hidden" name="SystemEventForm[system_event_active]" id="systemEventActive" value="<?= $model->active ?>">
                <?= $this->render('_form_builded_by_type', ['systemEvent' => $model, 'model' => $modelForm, 'formBuilder' => $formBuilder, 'type' => $type]) ?>
            <?php endif; ?>
        </div>
    </div>
</div>
<?php ActiveForm::end(); ?>
<?php Modal::end() ?>

BuilderFormByDynamicAttrs/SystemEvent/views/default/_form_builded_by_type.php
<?php

use app\widgets\ActiveForm;
use app\modules\SystemEvent\models\{
    SystemEvent,
    SystemEventModelPlaceholder,
    SystemEventType,
    SystemEventTypeSetting,
};
use app\modules\SystemEvent\models\form\SystemEventForm;
use app\modules\SystemEvent\components\FormBuilder;
use app\modules\SystemEvent\components\DTO\FormBuildDataDto;
use app\models\TaskStage;
use yii\helpers\Url;
use yii\bootstrap\Html;

/**
 * @var SystemEventType        $type
 * @var SystemEventTypeSetting $systemEventTypeSettingItem
 * @var FormBuilder            $formBuilder
 * @var SystemEventForm        $model
 * @var SystemEvent            $systemEvent
 */
$form = ActiveForm::begin(
    [
        'enableClientValidation' => true,
        'enableAjaxValidation' => true,
        'validationUrl' => Url::to('/default/validation-form-build'),
    ]
);
$groupFieldTab = [];
?>
<?= $systemEvent->isNewRecord ? '<hr>' : '' ?>
<?php
foreach ($type->systemEventTypeSettings as $systemEventTypeSettingItem) {
    $builderDto = new FormBuildDataDto($form, $model, $systemEventTypeSettingItem);
    if (!in_array($systemEventTypeSettingItem->slug, ['list_email', 'subject_mail', 'text_mail', 'text_for_informer'])) {
        if ($systemEventTypeSettingItem->slug === 'stage') {
            if (!$systemEvent->isNewRecord) {
                $builderDto->dataFields['dropdown']['stage'] = TaskStage::getStageList($systemEvent->systemEventMailSettings->workflow);
                echo $formBuilder->build($builderDto);
            } else {
                echo $formBuilder->build($builderDto);
            }
        } else {
            echo $formBuilder->build($builderDto);
        }
    } elseif ($systemEventTypeSettingItem->slug === 'text_for_informer') {
        $groupFieldTab['informer'][] = $formBuilder->build($builderDto);
    } else {
        $groupFieldTab['email'][$systemEventTypeSettingItem->slug] = $formBuilder->build($builderDto);
    }
}
?>

<nav id="systemEventNav" class="nav nav-pills nav-fill" role="tablist">
    <a class="nav-item nav-link active" id="pills-email-tab" href="#pills-email" aria-controls="pills-email"
       role="tab" data-toggle="pill" aria-selected="true">
        <?= Yii::t('app', 'Email message') ?>
    </a>
    <a class="nav-item nav-link" id="pills-informer-tab" href="#pills-informer" aria-controls="pills-design" role="tab"
       data-toggle="pill" aria-selected="false">
        <?= Yii::t('app', 'Message for informer') ?>
    </a>
</nav>

<div class="tab-content">
    <div role="tabpanel" aria-labelledby="pills-email-tab" class="tab-pane fade show active" id="pills-email">
        <?= $groupFieldTab['email']['subject_mail'] ?>
        <?= $groupFieldTab['email']['list_email'] ?>
        <?= $groupFieldTab['email']['text_mail'] ?>
    </div>
    <div role="tabpanel" aria-labelledby="pills-informer-tab" class="tab-pane fade" id="pills-informer">
        <?php foreach ($groupFieldTab['informer'] as $informerField): ?>
            <?= $informerField ?>
        <?php endforeach; ?>
    </div>
</div>
<?php ActiveForm::end() ?>
<div class="row">
    <div class="col-lg-24">
        <div class="placeholders">
            <?php if ($entities = $type->placeholders): ?>
                <?= Yii::t('app', 'В текст сообщения можно добавить переменные') . ': ' . implode(
                    ', ',
                    array_map(
                        function (SystemEventModelPlaceholder $item) {
                            return Html::tag(
                                'span',
                                $item->placeholder,
                                [
                                    'title' => $item->description,
                                    'class' => 'badge',
                                ]
                            );
                        },
                        $entities
                    )
                ) ?>
            <?php endif; ?>
        </div>
    </div>
</div>
<br/>

BuilderFormByDynamicAttrs/SystemEvent/views/default/_search.php
<?php

use app\modules\SystemEvent\models\search\SystemEventSearch;
use yii\helpers\Html;
use app\widgets\Select;
use yii\widgets\ActiveForm;
use app\modules\SystemEvent\helpers\SystemEventHelper;

/**
 * @var yii\web\View           $this
 * @var SystemEventSearch      $model
 * @var yii\widgets\ActiveForm $form
 */
?>
<div id="js-filter-form" style="display: <?= $model->hasErrors() ? 'block' : 'none' ?>;">
    <?php $form = ActiveForm::begin(
        [
            'action' => ['index'],
            'method' => 'get',
            'options' => ['autocomplete' => 'off'],
            'enableClientValidation' => true,
            'enableAjaxValidation' => true,
        ]
    ) ?>
    <section class="content--filters">
        <h2 class="title"><?= Yii::t('app', 'Фильтр') ?></h2>
        <div class="row">
            <div class="col-sm-12">
                <?= $form->field($model, 'typeId')->widget(
                    Select::class,
                    [
                        'options' => [
                            'class' => 'form-control input-sm',
                            'data-style' => 'btn-sm btn-default',
                            'prompt' => Yii::t('app', 'Не выбрано'),
                        ],
                        'items' => SystemEventHelper::getListSystemEventType(),
                    ]
                )->label(Yii::t('app', 'Тип обработчика')) ?>
            </div>
            <div class="col-sm-12">
                <?= $form->field($model, 'active')->dropDownList(SystemEventHelper::getDropdownActiveEvent())
                    ->label(Yii::t('app', 'Статус'))  ?>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                    <label for="" class="control-label">&nbsp;</label>
                    <div class="content--filters--action">
                        <?= Html::submitButton(Yii::t('app', 'Показать'), ['class' => 'btn btn-green']) ?>
                        <?= Html::a(Yii::t('app', 'Сброс'), ['index'], ['class' => 'btn btn-default']) ?>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <?php ActiveForm::end(); ?>
</div>

BuilderFormByDynamicAttrs/SystemEvent/views/default/_show_button_action.php
<?php

use yii\helpers\Html;
use yii\bootstrap\Modal;

/**
 * @var array $actions
 */
?>

<?php if ($actions): ?>
    <div class="btn-group" role="group">
        <button id="btn-action-system-event" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="false" style="width: 190px">
            <?= Yii::t('app', 'Действия') ?>
        </button>
        <div class="dropdown-menu btn-batch-action" aria-labelledby="btn-action-system-event" style="width: 190px">
            <?php foreach ($actions as $action): ?>
                <?= Html::a($action['label'], $action['url'], $action['options']) ?>
            <?php endforeach; ?>
        </div>
    </div>

    <?php Modal::begin(
        [
            'size' => 'modal-md',
            'bodyOptions' => [
                'style' => 'padding:20px',
                'class' => 'modal-body',
            ],
            'options' => [
                'id' => 'modal-change-stage-syst-event',
            ],
            'header' => '<h5 class="modal-title">' . Yii::t('app', '') . '</h5>',
            'footer' =>
                Html::button(Yii::t('app', 'Подтвердить'), ['class' => 'btn btn-green', 'id' => 'js-approve-action'])
                . Html::button(
                    Yii::t('app', 'Отменить'),
                    ['class' => 'btn btn-outline btn-outline--green', 'data-dismiss' => 'modal', 'id' => 'js-dismiss-modal']
                ),
        ]
    ); ?>
    <?php Modal::end(); ?>
<?php endif; ?>

BuilderFormByDynamicAttrs/SystemEvent/views/default/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\modules\SystemEvent\models\SystemEvent */

$this->title = Yii::t('app', 'Create System Event');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'System Events'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="system-event-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

BuilderFormByDynamicAttrs/SystemEvent/views/default/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use app\models\User;
use app\modules\SystemEvent\models\SystemEvent;

/* @var $this yii\web\View */
/* @var $actions array */
/* @var $searchModel app\modules\SystemEvent\models\search\SystemEventSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
$this->title = Yii::t('app', 'System Events');
$this->params['breadcrumbs'][] = $this->title;
$this->registerJs("RDS.EventList();");
?>

<div class="content--header">
    <h1 class="title"><?= $this->title ?></h1>
    <div class="content--header--toolbar">
        <?php if (Yii::$app->user->can(User::SYSTEM_EVENT_CREATE)): ?>
            <?= Html::a(Yii::t('app', 'Добавить'), ['create'], ['class' => 'btn btn-green js-show-modal']) ?>
        <?php endif ?>
        <?= $this->render('_show_button_action', ['actions' => $actions]) ?>
        <?= Html::a(Yii::t('app', 'Фильтр'), '#', ['class' => 'btn btn-outline btn-outline--green', 'id' => 'js-filter-toggle']) ?>
    </div>
</div>

<?= $this->render('_search', ['model' => $searchModel]) ?>

<?= GridView::widget(
    [
        'tableOptions' => ['class' => 'table table-striped'],
        'dataProvider' => $dataProvider,
        'rowOptions' => function ($model) {
            return ['class' => 'se-item', 'data-id' => $model->id];
        },
        'columns' => [
            'id',
            [
                'attribute' => 'type.title',
                'label' => Yii::t('app', 'Тип обработчика'),
            ],
            [
                'attribute' => 'event_name',
                'label' => Yii::t('app', 'Событие \ Обработчик'),
            ],
            [
                'attribute' => 'type.description',
                'value' => function (SystemEvent $model) {
                    return Yii::$app->systemEventFormatter->formatSystemEventDescrWithWorkflow($model);
                },
            ],
            [
                'attribute' => 'systemEventMailSettings.text_for_informer',
                'format' => 'raw',
                'value' => function (SystemEvent $model) {
                    return Html::activeCheckbox(
                        $model->systemEventMailSettings,
                        'text_for_informer',
                        ['disabled' => true, 'checked' => (bool) $model->systemEventMailSettings->text_for_informer, 'label' => false]
                    );
                },
            ],
            [
                'attribute' => 'active',
                'label' => Yii::t('app', 'Вкл.\Выкл'),
                'format' => 'raw',
                'value' => function (SystemEvent $model) {
                    return Html::activeCheckbox(
                        $model,
                        'active',
                        ['disabled' => true, 'checked' => (bool) $model->active, 'label' => false]
                    );
                },
            ],
            [
                'header' => Yii::t('app', 'Действия'),
                'class' => 'yii\grid\ActionColumn',
                'template' => '{update} {delete}',
                'buttons' => [
                    'update' => function ($url) {
                        return Html::a(
                            Yii::t('app', '<span class="svg--icon svg--edit" data-grunticon-embed></span>'),
                            $url,
                            [
                                'title' => Yii::t('app', 'Редактировать'),
                                'class' => 'btn-icon js-show-modal',
                            ]
                        );
                    },
                    'delete' => function ($url) {
                        return Html::a(
                            Yii::t('app', '<span class="svg--icon svg--delete" data-grunticon-embed></span>'),
                            $url,
                            [
                                'title' => Yii::t('app', 'Удалить'),
                                'class' => 'btn-icon js-delete',
                                'data-method' => 'post'
                            ]
                        );
                    },
                ],
            ],
        ],
    ]
); ?>

BuilderFormByDynamicAttrs/SystemEvent/views/default/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\modules\SystemEvent\models\SystemEvent */

$this->title = Yii::t('app', 'Update System Event: {name}', [
    'name' => $model->id,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'System Events'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="system-event-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

BuilderFormByDynamicAttrs/SystemEvent/views/default/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\modules\SystemEvent\models\SystemEvent */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'System Events'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="system-event-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'handler',
            'params',
            'user_id',
            'created_at',
            'updated_at',
            'type_id',
        ],
    ]) ?>

</div>